# Generated by Django 3.2.16 on 2023-05-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hit_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='description',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='hit',
            name='assignee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='hit_management.hitman'),
        ),
        migrations.AlterField(
            model_name='hitman',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
